feat(husky): update husky

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,5 +1,9 @@
 echo '📝 Checking the commit message'
 
-yarn commitlint --edit
+# Run commitlint to validate the commit message
+yarn commitlint --edit || {
+  echo '❌ Commit message check failed. Please follow the commit message guidelines and try again.'
+  exit 1
+}
 
-echo '✅✅ Very good! Committing your changes now'
+echo '✅ Commit message is valid! Committing your changes now.'
diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,20 +1,17 @@
-echo '🩺 Starting the checkout'
+echo '🩺 Starting pre-commit checks'
 
-#yarn lint-staged
-
-# Check ESLint Standards
+# Run ESLint on staged files
 yarn run eslint ||
 (
-  echo '⚙️❌ ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
-  false;
+  echo '⚙️❌ ESLint Check Failed. Make the required changes listed above, add changes, and try to commit again.'
+  exit 1
 )
 
-# Check tsconfig standards
+# Run Prettier to format files
 yarn run prettier ||
 (
-  echo '🤡❌ Failed Type check. Make the changes required above.'
-  false;
+  echo '🎨❌ Prettier Formatting Failed. Make the changes required above.'
+  exit 1
 )
 
-# If everything passes... Now we can commit
-echo '✅ Every test passed!'
+echo '✅ All pre-commit checks passed!'
